plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation ('com.googlecode.json-simple:json-simple:1.1.1') {
        exclude group: 'junit'
    }
    implementation 'org.javassist:javassist:3.30.2-GA'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
